version: '3.5'
volumes:
  vault:
networks:
  net:
services:
  docker-nginx:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html/
      - ./nginx:/etc/nginx/conf.d
    networks:
      - net
  docker-mariadb:
    image: mariadb
    volumes:
      - vault:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    networks:
      - net
  docker-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=docker-mariadb
    networks:
      - net
  docker-php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./:/var/www/
    networks:
      - net
