---
# tasks file for setups
- name: Yum install epel
  yum: 
    name: epel-release
    state: present

- name: Yum update
  yum:
    name: "*"
    state: latest

- name:
  yum:
    name:
      - vim
      - wget
      - bash-completion
      - htop
    state: present
