---
# defaults file for PRODUCTION
hosts: clients
become: yes
user: ansible
ansible_ssh_user:  ansible
host_key_checking: False
ansible_sudo_pass: ansible
ansible_ssh_private_key: /home/ansible/.ssh/id_rsa