---
# defaults file for PRODUCTION
become: yes
user: ansible
ansible_become_pass : vagrant
ansible_user: vagrant
ansible_ssh_user:  vagrant
host_key_checking: False
ansible_sudo_pass: vagrant
ansible_ssh_private_key: /home/vagrant/.ssh/id_rsa
